from pathlib import Path
p=Path('public/index.html')
s=p.read_text(encoding='utf-8')

sidebar='''<style id="cutziSidebarDensityV1003">\n/* v100.3 — desktop sidebar density based on the compact Cheffli rhythm.\n   Keep rows at their natural height instead of stretching them over the full sidebar. */\n@media(min-width:1101px){\n  .sidebar .brand{padding-bottom:12px!important}\n  .sidebar .navgroup{\n    align-content:start!important;\n    grid-auto-rows:max-content!important;\n    gap:2px!important;\n  }\n  .sidebar .navgroup>.navlabel{\n    padding:7px 11px 3px!important;\n    min-height:16px!important;\n    line-height:16px!important;\n  }\n  .sidebar .navgroup>.navlabel:first-child{\n    padding-top:4px!important;\n  }\n  .sidebar .navbtn{\n    height:38px!important;\n    min-height:38px!important;\n    border-radius:14px!important;\n  }\n  .sidebar-account-nav-v88{\n    align-content:start!important;\n    grid-auto-rows:max-content!important;\n    gap:2px!important;\n    margin-top:5px!important;\n    padding:6px 0 2px!important;\n  }\n  .sidebar-account-nav-v88 .navlabel{\n    min-height:16px!important;\n    line-height:16px!important;\n    padding:0 11px 3px!important;\n  }\n  .sidebar-account-footer{\n    margin-top:2px!important;\n    padding-top:6px!important;\n  }\n}\n</style>\n'''
if 'id="cutziSidebarDensityV1003"' not in s:
    s=s.replace('</head>',sidebar+'\n</head>',1)

old_local="function attemptLogin(){const email=(document.getElementById('loginEmail').value||'').trim().toLowerCase(),password=document.getElementById('loginPassword').value||'',error=document.getElementById('loginError');if(!email||!password){error.textContent='Vul je e-mailadres en wachtwoord in.';error.classList.add('show');return false}const accounts=loadPrototypeAccounts();if(!accounts.length){error.textContent='Nog geen lokaal account gevonden. Maak eerst een account aan.';error.classList.add('show');return false}const account=accounts.find(a=>String(a.email||'').toLowerCase()===email&&a.passwordFingerprint===prototypePasswordFingerprint(password));if(!account){error.textContent='E-mailadres of wachtwoord klopt niet.';error.classList.add('show');return false}localStorage.setItem(AUTH_ACTIVE_ACCOUNT_KEY,account.id);if(account.salonName){state.branding=state.branding||{};state.branding.salonName=account.salonName;persistState();renderBranding()}error.classList.remove('show');closeLogin();showToast('Welkom, '+(account.fullName?.split(/\\s+/)[0]||account.fullName));return true}\n\n\n/* v100 ONLINE SHARED TEST"
new_local="async function attemptLogin(){return attemptOnlineLoginV1005()}\n\n\n/* v100.4 LOGIN STABILITY — cloud auth is separated from the salon-state load, with cookie-safe retries. */\n/* v100.5 LOGIN FIX — one authoritative online login handler; legacy local auth can no longer intercept submit. */\n/* v100 ONLINE SHARED TEST"
assert old_local in s, 'old local login block not found'
s=s.replace(old_local,new_local,1)

old_api="""async function cutziApi(path,options={}){\n  const init={credentials:'same-origin',...options};\n  init.headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};\n  const res=await fetch(CUTZI_ONLINE_API+path,init);\n  let data={};try{data=await res.json()}catch(_){data={}}\n  if(!res.ok){const err=new Error(data?.error||'Cloud request failed');err.status=res.status;err.data=data;throw err}\n  return data;\n}\n"""
new_api="""async function cutziApi(path,options={}){\n  const init={credentials:'include',cache:'no-store',...options};\n  init.headers={...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};\n  const res=await fetch(CUTZI_ONLINE_API+path,init);\n  let data={};try{data=await res.json()}catch(_){data={}}\n  if(!res.ok){const err=new Error(data?.error||'Cloud request failed');err.status=res.status;err.data=data;throw err}\n  return data;\n}\nfunction cutziWaitV1004(ms){return new Promise(resolve=>setTimeout(resolve,ms))}\nasync function pullCloudStateWithRetryV1004(attempts=3){\n  let lastErr=null;\n  for(let i=0;i<attempts;i++){\n    try{return await pullCloudState(true)}catch(err){lastErr=err;if(i<attempts-1)await cutziWaitV1004(120*(i+1))}\n  }\n  throw lastErr||new Error('Salondata kon niet worden geladen');\n}\n"""
assert old_api in s, 'old api block not found'
s=s.replace(old_api,new_api,1)

old_online="""attemptLogin=async function(){\n  const email=(document.getElementById('loginEmail').value||'').trim().toLowerCase(),password=document.getElementById('loginPassword').value||'',remember=!!document.getElementById('loginRemember')?.checked,error=document.getElementById('loginError');\n  if(!email||!password){error.textContent='Vul je e-mailadres en wachtwoord in.';error.classList.add('show');return false}\n  try{\n    const payload=await cutziApi('/login',{method:'POST',body:JSON.stringify({email,password,remember})});\n    cutziCloudAccount=payload.account;await pullCloudState(true);cutziCloudReady=true;error.classList.remove('show');closeLogin();renderCloudSyncedState();showToast('Welkom, '+(cutziCloudAccount?.fullName?.split(/\\s+/)[0]||'terug'));return true;\n  }catch(err){error.textContent=err.status===401?'E-mailadres of wachtwoord klopt niet.':(err.data?.error||'Inloggen mislukt. Controleer je verbinding.');error.classList.add('show');return false}\n};\n"""
new_online="""async function attemptOnlineLoginV1005(){\n  const email=(document.getElementById('loginEmail').value||'').trim().toLowerCase(),password=document.getElementById('loginPassword').value||'',remember=!!document.getElementById('loginRemember')?.checked,error=document.getElementById('loginError'),submit=document.getElementById('loginSubmit');\n  if(!email||!password){error.textContent='Vul je e-mailadres en wachtwoord in.';error.classList.add('show');return false}\n  error.classList.remove('show');if(submit){submit.disabled=true;submit.dataset.originalText=submit.textContent;submit.textContent='Inloggen…'}\n  let payload;\n  try{\n    payload=await cutziApi('/login',{method:'POST',body:JSON.stringify({email,password,remember})});\n  }catch(err){\n    error.textContent=err.status===401?'E-mailadres of wachtwoord klopt niet.':(err.data?.error||'Inloggen mislukt. Controleer je verbinding.');error.classList.add('show');\n    if(submit){submit.disabled=false;submit.textContent=submit.dataset.originalText||'Inloggen'}\n    return false;\n  }\n  cutziCloudAccount=payload.account;\n  try{\n    await cutziWaitV1004(80);\n    await pullCloudStateWithRetryV1004(3);\n  }catch(stateErr){\n    let sessionOk=false;\n    try{const me=await cutziApi('/me');cutziCloudAccount=me.account||cutziCloudAccount;sessionOk=true}catch(_){}\n    error.textContent=sessionOk?'Je login is aanvaard, maar de salondata kon niet worden geladen. Vernieuw de pagina en probeer opnieuw.':'Je login is aanvaard, maar de beveiligde sessie kon niet worden gestart. Vernieuw de pagina en probeer opnieuw.';\n    error.classList.add('show');cutziCloudReady=false;\n    if(submit){submit.disabled=false;submit.textContent=submit.dataset.originalText||'Inloggen'}\n    return false;\n  }\n  cutziCloudReady=true;error.classList.remove('show');closeLogin();renderCloudSyncedState();showToast('Welkom, '+(cutziCloudAccount?.fullName?.split(/\\s+/)[0]||'terug'));\n  if(submit){submit.disabled=false;submit.textContent=submit.dataset.originalText||'Inloggen'}\n  return true;\n};\n"""
assert old_online in s, 'old online login block not found'
s=s.replace(old_online,new_online,1)

old_listener="document.getElementById('loginFormV22').addEventListener('submit',e=>{e.preventDefault();attemptLogin()});"
new_listener="document.getElementById('loginFormV22').addEventListener('submit',async e=>{e.preventDefault();await attemptLogin()});"
assert old_listener in s, 'old submit listener not found'
s=s.replace(old_listener,new_listener,1)

p.write_text(s,encoding='utf-8')
